    @Override
    public synchronized void close() throws LockReleaseFailedException {
      // TODO: wierd that clearLock() throws the raw IOException...
      if (obtained) {
        try {
          Files.deleteIfExists(lockFile);
        } catch (Throwable cause) {
          throw new LockReleaseFailedException("failed to delete " + lockFile, cause);
        } finally {
          obtained = false;
        }
      }
    }

