  @Test
  public void testRequestStatusUnexpectedFailuresResultIn500Exception() {
    final Throwable cause = new NullPointerException();
    whenUnexpectedErrorOccursDuringCoreAdminOp(cause);
    
    try {
      CoreAdminOperation.REQUESTSTATUS_OP.execute(callInfo);
      fail("Expected request-status execution to fail with exception.");
    } catch  (Exception thrown) {
      assertSolrExceptionWithCodeAndCause(thrown, ErrorCode.SERVER_ERROR.code, cause);
    }
  }

