  @Test
  public void testCreateSnapshotUnexpectedFailuresResultIn500Exception() {
    final Throwable cause = new NullPointerException();
    whenUnexpectedErrorOccursDuringCoreAdminOp(cause);

    Exception ex = expectThrows(Exception.class, () ->  CoreAdminOperation.CREATESNAPSHOT_OP.execute(callInfo));
    assertSolrExceptionWithCodeAndCause(ex, ErrorCode.SERVER_ERROR.code, cause);
  }

