  @Test
  public void testReloadUnexpectedFailuresResultIn500SolrException() {
    final Throwable cause = new NullPointerException();
    whenUnexpectedErrorOccursDuringCoreAdminOp(cause);
    
    try {
      CoreAdminOperation.RELOAD_OP.execute(callInfo);
      fail("Expected core-reload execution to fail with exception.");
    } catch  (Exception thrown) {
      assertSolrExceptionWithCodeAndCause(thrown, ErrorCode.SERVER_ERROR.code, cause);
    }
  }

