  @Test
  public void testRenameUnexpectedFailuresResultIn500SolrException() {
    final Throwable cause = new NullPointerException();
    whenUnexpectedErrorOccursDuringCoreAdminOp(cause);

    Exception ex = expectThrows(Exception.class, () ->  CoreAdminOperation.RENAME_OP.execute(callInfo));
    assertSolrExceptionWithCodeAndCause(ex, ErrorCode.SERVER_ERROR.code, cause);
  }

